server:
  port: 8082

spring:
  application:
    name: hacked-backend

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: DEBUG
    com.hacked: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.security: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG
